In [1]:
%matplotlib notebook

In [2]:
# Dependencies
import matplotlib.pyplot as plt
from stats import median
import numpy as np

In [3]:
### Data Points
arr = np.array([2.3, 10.2,11.2, 12.3, 14.5, 14.6, 15.0, 15.1, 19.0, 24.0])
arr

array([ 2.3, 10.2, 11.2, 12.3, 14.5, 14.6, 15. , 15.1, 19. , 24. ])

In [5]:
# Find the median
med=median(arr)
print(f"Median: {med}")

Median: 14.55


In [9]:
# Use numpy to create quartiles
q1=np.percentile(arr, 25)
q3=np.percentile(arr, 75)


In [8]:
# Print the quartiles
print(f"Q1: {q1}")
print(f"Q3: {q3}")

Q1: 11.474999999999998
Q3: 15.075


In [10]:
# Calculate the interquartile range
iqr=q3-q1

In [12]:
# Find lower boundary
# Q1 - 1.5 * IQR
lower_boundary=q1-(1.5*iqr)

In [16]:
# Find upper boundary
# Q3 + 1.5 * IQR
upper_boundary=q3+(1.5*iqr)

In [14]:
# Check for any lower outliers
arr[arr <= lower_boundary]

array([2.3])

In [17]:
# Check for any upper outliers
arr[arr>=upper_boundary]

array([24.])

In [12]:
# Create box plot